-- MySQL Script generated by MySQL Workbench
-- Tue Aug 12 20:20:36 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema e2496310
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema e2496310
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `e2496310` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci ;
USE `e2496310` ;

-- -----------------------------------------------------
-- Table `e2496310`.`membre`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `e2496310`.`membre` (
  `id_membre` INT NOT NULL AUTO_INCREMENT COMMENT 'Unique identifier for the member',
  `nom_utilisateur` VARCHAR(100) NOT NULL COMMENT 'Unique username for the member',
  `courriel` VARCHAR(255) NOT NULL COMMENT 'Email address of the member',
  `mot_de_passe` VARCHAR(255) NOT NULL COMMENT 'Hashed password of the member',
  `historique_offres` TEXT NULL DEFAULT NULL COMMENT 'JSON string storing the member\'s bidding history (can be normalized later)',
  `profil_acheteur` TEXT NULL DEFAULT NULL COMMENT 'JSON string storing relevant buyer profile information (can be normalized later)',
  `date_inscription` DATETIME NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Date and time of member registration',
  PRIMARY KEY (`id_membre`),
  UNIQUE INDEX `nom_utilisateur` (`nom_utilisateur` ASC) VISIBLE,
  UNIQUE INDEX `courriel` (`courriel` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 18
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_general_ci
COMMENT = 'Table to store user accounts and profiles.';


-- -----------------------------------------------------
-- Table `e2496310`.`timbre`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `e2496310`.`timbre` (
  `id_timbre` INT NOT NULL AUTO_INCREMENT COMMENT 'Unique identifier for the stamp',
  `nom` VARCHAR(255) NOT NULL COMMENT 'Name of the stamp',
  `date_creation` DATE NULL DEFAULT NULL COMMENT 'Date the stamp was created or issued',
  `couleurs` VARCHAR(255) NULL DEFAULT NULL COMMENT 'Description of the stamp colors',
  `pays_origine` VARCHAR(100) NULL DEFAULT NULL COMMENT 'Country of origin of the stamp',
  `image_principale` VARCHAR(255) NULL DEFAULT NULL COMMENT 'URL or path to the main image of the stamp',
  `images_supplementaires` TEXT NULL DEFAULT NULL COMMENT 'JSON array of URLs or paths to additional stamp images',
  `condition` ENUM('Parfaite', 'Excellente', 'Bonne', 'Moyenne', 'Endommagé') NULL DEFAULT NULL COMMENT 'Physical condition of the stamp',
  `tirage` INT NULL DEFAULT NULL COMMENT 'Number of copies produced (edition size)',
  `dimensions` VARCHAR(50) NULL DEFAULT NULL COMMENT 'Physical dimensions of the stamp (e.g., \"25x30mm\")',
  `certifie` TINYINT(1) NULL DEFAULT '0' COMMENT 'Indicates if the stamp is certified (TRUE/FALSE)',
  PRIMARY KEY (`id_timbre`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_general_ci
COMMENT = 'Table to store details about collectible stamps.';


-- -----------------------------------------------------
-- Table `e2496310`.`enchere`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `e2496310`.`enchere` (
  `id_enchere` INT NOT NULL AUTO_INCREMENT COMMENT 'Unique identifier for the auction',
  `id_timbre` INT NOT NULL COMMENT 'Foreign key to Timbre table (one-to-one relationship)',
  `id_membre` INT NOT NULL COMMENT 'Foreign key to Membre table (the member who published the auction)',
  `date_debut` DATETIME NOT NULL COMMENT 'Start date and time of the auction',
  `date_fin` DATETIME NOT NULL COMMENT 'End date and time of the auction',
  `prix_plancher` DECIMAL(10,2) NOT NULL COMMENT 'Minimum bid price for the auction',
  `coup_de_coeur_lord` TINYINT(1) NULL DEFAULT '0' COMMENT 'Indicates if the auction is a Lord\'s favorite (TRUE/FALSE)',
  `statut` ENUM('Active', 'Archivée', 'Terminée') NULL DEFAULT 'Active' COMMENT 'Current status of the auction',
  PRIMARY KEY (`id_enchere`),
  UNIQUE INDEX `id_timbre` (`id_timbre` ASC) VISIBLE,
  INDEX `fk_enchere_membre` (`id_membre` ASC) VISIBLE,
  CONSTRAINT `fk_enchere_membre`
    FOREIGN KEY (`id_membre`)
    REFERENCES `e2496310`.`membre` (`id_membre`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_enchere_timbre`
    FOREIGN KEY (`id_timbre`)
    REFERENCES `e2496310`.`timbre` (`id_timbre`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_general_ci
COMMENT = 'Table to manage auction details for stamps.';


-- -----------------------------------------------------
-- Table `e2496310`.`favoris`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `e2496310`.`favoris` (
  `id_membre` INT NOT NULL COMMENT 'Foreign key to Membre table',
  `id_enchere` INT NOT NULL COMMENT 'Foreign key to Enchere table',
  `date_ajout` DATETIME NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Date and time the auction was added to favorites',
  PRIMARY KEY (`id_membre`, `id_enchere`),
  INDEX `fk_favoris_enchere` (`id_enchere` ASC) VISIBLE,
  CONSTRAINT `fk_favoris_enchere`
    FOREIGN KEY (`id_enchere`)
    REFERENCES `e2496310`.`enchere` (`id_enchere`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_favoris_membre`
    FOREIGN KEY (`id_membre`)
    REFERENCES `e2496310`.`membre` (`id_membre`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_general_ci
COMMENT = 'Table to store member favorite auctions.';


-- -----------------------------------------------------
-- Table `e2496310`.`images`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `e2496310`.`images` (
  `id_image` INT NOT NULL AUTO_INCREMENT,
  `id_timbre` INT NOT NULL,
  `chemin` VARCHAR(255) NOT NULL,
  `est_principale` TINYINT(1) NULL DEFAULT '0',
  PRIMARY KEY (`id_image`),
  INDEX `id_timbre` (`id_timbre` ASC) VISIBLE,
  CONSTRAINT `images_ibfk_1`
    FOREIGN KEY (`id_timbre`)
    REFERENCES `e2496310`.`timbre` (`id_timbre`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_general_ci;


-- -----------------------------------------------------
-- Table `e2496310`.`offre`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `e2496310`.`offre` (
  `id_offre` INT NOT NULL AUTO_INCREMENT COMMENT 'Unique identifier for the bid',
  `id_enchere` INT NOT NULL COMMENT 'Foreign key to Enchere table',
  `id_membre` INT NOT NULL COMMENT 'Foreign key to Membre table (the member who placed the bid)',
  `montant` DECIMAL(10,2) NOT NULL COMMENT 'Amount of the bid',
  `date_offre` DATETIME NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Date and time the bid was placed',
  PRIMARY KEY (`id_offre`),
  INDEX `fk_offre_enchere` (`id_enchere` ASC) VISIBLE,
  INDEX `fk_offre_membre` (`id_membre` ASC) VISIBLE,
  CONSTRAINT `fk_offre_enchere`
    FOREIGN KEY (`id_enchere`)
    REFERENCES `e2496310`.`enchere` (`id_enchere`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_offre_membre`
    FOREIGN KEY (`id_membre`)
    REFERENCES `e2496310`.`membre` (`id_membre`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_general_ci
COMMENT = 'Table to record bids placed on auctions.';


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
