-- MySQL Script generated by MySQL Workbench
-- Updated Physical Data Model (MPD) for Stampee Auction System
-- Based on current implementation analysis

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema stampee_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `stampee_db` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ;
USE `stampee_db` ;

-- -----------------------------------------------------
-- Table `stampee_db`.`membre`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `stampee_db`.`membre` (
  `id_membre` INT NOT NULL AUTO_INCREMENT COMMENT 'Unique identifier for the member',
  `nom_utilisateur` VARCHAR(100) NOT NULL COMMENT 'Unique username for the member',
  `courriel` VARCHAR(255) NOT NULL COMMENT 'Email address of the member',
  `mot_de_passe` VARCHAR(255) NOT NULL COMMENT 'Hashed password of the member',
  `role` ENUM('utilisateur', 'admin', 'lord') NULL DEFAULT 'utilisateur' COMMENT 'User role in the system',
  `date_inscription` DATETIME NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Date and time of member registration',
  `derniere_connexion` DATETIME NULL DEFAULT NULL COMMENT 'Last login timestamp',
  `statut_compte` ENUM('actif', 'suspendu', 'supprime') NULL DEFAULT 'actif' COMMENT 'Account status',
  PRIMARY KEY (`id_membre`),
  UNIQUE INDEX `uk_nom_utilisateur` (`nom_utilisateur` ASC) VISIBLE,
  UNIQUE INDEX `uk_courriel` (`courriel` ASC) VISIBLE,
  INDEX `idx_role` (`role` ASC) VISIBLE,
  INDEX `idx_statut_compte` (`statut_compte` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci
COMMENT = 'Table to store user accounts and profiles.';

-- -----------------------------------------------------
-- Table `stampee_db`.`timbre`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `stampee_db`.`timbre` (
  `id_timbre` INT NOT NULL AUTO_INCREMENT COMMENT 'Unique identifier for the stamp',
  `nom` VARCHAR(255) NOT NULL COMMENT 'Name of the stamp',
  `date_creation` DATE NULL DEFAULT NULL COMMENT 'Date the stamp was created or issued',
  `couleurs` VARCHAR(255) NULL DEFAULT NULL COMMENT 'Description of the stamp colors',
  `pays_origine` VARCHAR(100) NULL DEFAULT NULL COMMENT 'Country of origin of the stamp',
  `condition` ENUM('Parfaite', 'Excellente', 'Bonne', 'Moyenne', 'Endommagé') NULL DEFAULT NULL COMMENT 'Physical condition of the stamp',
  `tirage` INT NULL DEFAULT NULL COMMENT 'Number of copies produced (edition size)',
  `dimensions` VARCHAR(50) NULL DEFAULT NULL COMMENT 'Physical dimensions of the stamp (e.g., "25x30mm")',
  `certifie` TINYINT(1) NULL DEFAULT 0 COMMENT 'Indicates if the stamp is certified (TRUE/FALSE)',
  `description` TEXT NULL DEFAULT NULL COMMENT 'Detailed description of the stamp',
  `valeur_estimee` DECIMAL(10,2) NULL DEFAULT NULL COMMENT 'Estimated value of the stamp',
  `date_ajout` DATETIME NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Date when stamp was added to system',
  PRIMARY KEY (`id_timbre`),
  INDEX `idx_pays_origine` (`pays_origine` ASC) VISIBLE,
  INDEX `idx_date_creation` (`date_creation` ASC) VISIBLE,
  INDEX `idx_condition` (`condition` ASC) VISIBLE,
  INDEX `idx_certifie` (`certifie` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci
COMMENT = 'Table to store details about collectible stamps.';

-- -----------------------------------------------------
-- Table `stampee_db`.`images`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `stampee_db`.`images` (
  `id_image` INT NOT NULL AUTO_INCREMENT COMMENT 'Unique identifier for the image',
  `id_timbre` INT NOT NULL COMMENT 'Foreign key to Timbre table',
  `chemin` VARCHAR(500) NOT NULL COMMENT 'File path or URL to the image',
  `nom_fichier` VARCHAR(255) NULL DEFAULT NULL COMMENT 'Original filename',
  `type_mime` VARCHAR(100) NULL DEFAULT NULL COMMENT 'MIME type of the image',
  `taille_fichier` INT NULL DEFAULT NULL COMMENT 'File size in bytes',
  `est_principale` TINYINT(1) NULL DEFAULT 0 COMMENT 'Indicates if this is the main image (TRUE/FALSE)',
  `date_ajout` DATETIME NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Date when image was uploaded',
  `ordre_affichage` INT NULL DEFAULT 0 COMMENT 'Display order for multiple images',
  PRIMARY KEY (`id_image`),
  INDEX `fk_images_timbre_idx` (`id_timbre` ASC) VISIBLE,
  INDEX `idx_est_principale` (`est_principale` ASC) VISIBLE,
  INDEX `idx_ordre_affichage` (`ordre_affichage` ASC) VISIBLE,
  CONSTRAINT `fk_images_timbre`
    FOREIGN KEY (`id_timbre`)
    REFERENCES `stampee_db`.`timbre` (`id_timbre`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci
COMMENT = 'Table to store stamp images with metadata.';

-- -----------------------------------------------------
-- Table `stampee_db`.`enchere`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `stampee_db`.`enchere` (
  `id_enchere` INT NOT NULL AUTO_INCREMENT COMMENT 'Unique identifier for the auction',
  `id_timbre` INT NOT NULL COMMENT 'Foreign key to Timbre table (one-to-one relationship)',
  `id_membre` INT NOT NULL COMMENT 'Foreign key to Membre table (the member who published the auction)',
  `date_debut` DATETIME NOT NULL COMMENT 'Start date and time of the auction',
  `date_fin` DATETIME NOT NULL COMMENT 'End date and time of the auction',
  `prix_plancher` DECIMAL(10,2) NOT NULL COMMENT 'Minimum bid price for the auction',
  `coup_de_coeur_lord` TINYINT(1) NULL DEFAULT 0 COMMENT 'Indicates if the auction is a Lord\'s favorite (TRUE/FALSE)',
  `statut` ENUM('Active', 'Archivée', 'Terminée', 'Annulée') NULL DEFAULT 'Active' COMMENT 'Current status of the auction',
  `description_enchere` TEXT NULL DEFAULT NULL COMMENT 'Additional auction description',
  `conditions_vente` TEXT NULL DEFAULT NULL COMMENT 'Terms and conditions of the sale',
  `date_creation` DATETIME NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Date when auction was created',
  `date_modification` DATETIME NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Date when auction was last modified',
  PRIMARY KEY (`id_enchere`),
  UNIQUE INDEX `uk_id_timbre` (`id_timbre` ASC) VISIBLE,
  INDEX `fk_enchere_membre_idx` (`id_membre` ASC) VISIBLE,
  INDEX `idx_date_debut` (`date_debut` ASC) VISIBLE,
  INDEX `idx_date_fin` (`date_fin` ASC) VISIBLE,
  INDEX `idx_statut` (`statut` ASC) VISIBLE,
  INDEX `idx_coup_de_coeur_lord` (`coup_de_coeur_lord` ASC) VISIBLE,
  INDEX `idx_prix_plancher` (`prix_plancher` ASC) VISIBLE,
  CONSTRAINT `fk_enchere_timbre`
    FOREIGN KEY (`id_timbre`)
    REFERENCES `stampee_db`.`timbre` (`id_timbre`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_enchere_membre`
    FOREIGN KEY (`id_membre`)
    REFERENCES `stampee_db`.`membre` (`id_membre`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci
COMMENT = 'Table to manage auction details for stamps.';

-- -----------------------------------------------------
-- Table `stampee_db`.`offre`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `stampee_db`.`offre` (
  `id_offre` INT NOT NULL AUTO_INCREMENT COMMENT 'Unique identifier for the bid',
  `id_enchere` INT NOT NULL COMMENT 'Foreign key to Enchere table',
  `id_membre` INT NOT NULL COMMENT 'Foreign key to Membre table (the member who placed the bid)',
  `montant` DECIMAL(10,2) NOT NULL COMMENT 'Amount of the bid',
  `date_offre` DATETIME NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Date and time the bid was placed',
  `statut` ENUM('active', 'retirée', 'gagnante', 'perdante') NULL DEFAULT 'active' COMMENT 'Status of the bid',
  `ip_adresse` VARCHAR(45) NULL DEFAULT NULL COMMENT 'IP address of the bidder',
  `user_agent` TEXT NULL DEFAULT NULL COMMENT 'User agent string for audit purposes',
  PRIMARY KEY (`id_offre`),
  INDEX `fk_offre_enchere_idx` (`id_enchere` ASC) VISIBLE,
  INDEX `fk_offre_membre_idx` (`id_membre` ASC) VISIBLE,
  INDEX `idx_montant` (`montant` ASC) VISIBLE,
  INDEX `idx_date_offre` (`date_offre` ASC) VISIBLE,
  INDEX `idx_statut` (`statut` ASC) VISIBLE,
  CONSTRAINT `fk_offre_enchere`
    FOREIGN KEY (`id_enchere`)
    REFERENCES `stampee_db`.`enchere` (`id_enchere`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_offre_membre`
    FOREIGN KEY (`id_membre`)
    REFERENCES `stampee_db`.`membre` (`id_membre`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci
COMMENT = 'Table to record bids placed on auctions.';

-- -----------------------------------------------------
-- Table `stampee_db`.`favoris`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `stampee_db`.`favoris` (
  `id_favoris` INT NOT NULL AUTO_INCREMENT COMMENT 'Unique identifier for the favorite',
  `id_membre` INT NOT NULL COMMENT 'Foreign key to Membre table',
  `id_enchere` INT NOT NULL COMMENT 'Foreign key to Enchere table',
  `date_ajout` DATETIME NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Date and time the auction was added to favorites',
  `note_personnelle` TEXT NULL DEFAULT NULL COMMENT 'Personal note about the favorite',
  PRIMARY KEY (`id_favoris`),
  UNIQUE INDEX `uk_membre_enchere` (`id_membre` ASC, `id_enchere` ASC) VISIBLE,
  INDEX `fk_favoris_enchere_idx` (`id_enchere` ASC) VISIBLE,
  INDEX `idx_date_ajout` (`date_ajout` ASC) VISIBLE,
  CONSTRAINT `fk_favoris_membre`
    FOREIGN KEY (`id_membre`)
    REFERENCES `stampee_db`.`membre` (`id_membre`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_favoris_enchere`
    FOREIGN KEY (`id_enchere`)
    REFERENCES `stampee_db`.`enchere` (`id_enchere`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci
COMMENT = 'Table to store member favorite auctions.';

-- -----------------------------------------------------
-- Table `stampee_db`.`historique_actions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `stampee_db`.`historique_actions` (
  `id_action` INT NOT NULL AUTO_INCREMENT COMMENT 'Unique identifier for the action',
  `id_membre` INT NULL DEFAULT NULL COMMENT 'Foreign key to Membre table (NULL if anonymous)',
  `type_action` ENUM('connexion', 'inscription', 'creation_enchere', 'placement_offre', 'ajout_favoris', 'modification_profil', 'suppression_compte') NOT NULL COMMENT 'Type of action performed',
  `description` TEXT NULL DEFAULT NULL COMMENT 'Description of the action',
  `ip_adresse` VARCHAR(45) NULL DEFAULT NULL COMMENT 'IP address of the user',
  `user_agent` TEXT NULL DEFAULT NULL COMMENT 'User agent string',
  `date_action` DATETIME NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Date and time of the action',
  `donnees_supplementaires` JSON NULL DEFAULT NULL COMMENT 'Additional data related to the action',
  PRIMARY KEY (`id_action`),
  INDEX `fk_historique_membre_idx` (`id_membre` ASC) VISIBLE,
  INDEX `idx_type_action` (`type_action` ASC) VISIBLE,
  INDEX `idx_date_action` (`date_action` ASC) VISIBLE,
  INDEX `idx_ip_adresse` (`ip_adresse` ASC) VISIBLE,
  CONSTRAINT `fk_historique_membre`
    FOREIGN KEY (`id_membre`)
    REFERENCES `stampee_db`.`membre` (`id_membre`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci
COMMENT = 'Table to log user actions for audit and analytics.';

-- -----------------------------------------------------
-- Table `stampee_db`.`categories_timbres`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `stampee_db`.`categories_timbres` (
  `id_categorie` INT NOT NULL AUTO_INCREMENT COMMENT 'Unique identifier for the category',
  `nom_categorie` VARCHAR(100) NOT NULL COMMENT 'Name of the category',
  `description` TEXT NULL DEFAULT NULL COMMENT 'Description of the category',
  `categorie_parent` INT NULL DEFAULT NULL COMMENT 'Parent category ID for hierarchical categories',
  `icone` VARCHAR(255) NULL DEFAULT NULL COMMENT 'Icon path for the category',
  `actif` TINYINT(1) NULL DEFAULT 1 COMMENT 'Whether the category is active',
  `date_creation` DATETIME NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Date when category was created',
  PRIMARY KEY (`id_categorie`),
  UNIQUE INDEX `uk_nom_categorie` (`nom_categorie` ASC) VISIBLE,
  INDEX `fk_categorie_parent_idx` (`categorie_parent` ASC) VISIBLE,
  INDEX `idx_actif` (`actif` ASC) VISIBLE,
  CONSTRAINT `fk_categorie_parent`
    FOREIGN KEY (`categorie_parent`)
    REFERENCES `stampee_db`.`categories_timbres` (`id_categorie`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci
COMMENT = 'Table to categorize stamps for better organization.';

-- -----------------------------------------------------
-- Table `stampee_db`.`timbres_categories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `stampee_db`.`timbres_categories` (
  `id_timbre` INT NOT NULL COMMENT 'Foreign key to Timbre table',
  `id_categorie` INT NOT NULL COMMENT 'Foreign key to Categories table',
  `date_ajout` DATETIME NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Date when category was assigned',
  PRIMARY KEY (`id_timbre`, `id_categorie`),
  INDEX `fk_timbres_categories_categorie_idx` (`id_categorie` ASC) VISIBLE,
  CONSTRAINT `fk_timbres_categories_timbre`
    FOREIGN KEY (`id_timbre`)
    REFERENCES `stampee_db`.`timbre` (`id_timbre`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_timbres_categories_categorie`
    FOREIGN KEY (`id_categorie`)
    REFERENCES `stampee_db`.`categories_timbres` (`id_categorie`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci
COMMENT = 'Junction table linking stamps to categories (many-to-many relationship).';

-- -----------------------------------------------------
-- Insert default categories
-- -----------------------------------------------------
INSERT INTO `stampee_db`.`categories_timbres` (`nom_categorie`, `description`) VALUES
('Classiques', 'Timbre classiques et traditionnels'),
('Commemoratifs', 'Timbre commémoratifs et événementiels'),
('Thématiques', 'Timbre avec des thèmes spécifiques'),
('Historiques', 'Timbre d\'importance historique'),
('Rares', 'Timbre rares et de collection');

-- -----------------------------------------------------
-- Insert default admin user
-- -----------------------------------------------------
INSERT INTO `stampee_db`.`membre` (`nom_utilisateur`, `courriel`, `mot_de_passe`, `role`) VALUES
('admin', 'admin@stampee.com', '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 'admin');

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;